spring.datasource.url=${jdbc:postgresql://dpg-d7957l9r0fns73eacp6g-a/hirehub_db_jk82}
spring.datasource.username=${hirehub_db_jk82_user}
spring.datasource.password=${T4Wf3IbVbACSeApg8AewGE1RTvqNMBk5}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}